# stack name: bn_directus

version: "3.9"

services:
  database:
    # Postgres runs on port 5432
    image: postgres:12
    volumes:
      - directusDataVol1:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'directus'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.project == bullenetwork ]
      labels:
        - traefik.enable=false

  cache:
    # Redis runs on port 6379
    image: redis:7
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.project == bullenetwork ]
      labels:
        - traefik.enable=false

  directus:
    # Directus runs on port 8055
    image: directus/directus:9
    networks:
      - internal
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.project == bullenetwork ]
      labels:
        - traefik.http.routers.bn_directus.rule=Host(`vanil.bullenetwork.ch`)
        - traefik.http.routers.bn_directus.entrypoints=websecure
        - traefik.http.routers.bn_directus.tls.certresolver=leresolver
        - traefik.http.services.bn_directus.loadbalancer.server.port=8055
    depends_on:
      - cache
      - database
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      STORAGE_LOCATIONS: gcs

      STORAGE_GCS_PUBLIC_URL: https://console.cloud.google.com/storage/browser/bullenetwork-directus-vanil/
      STORAGE_GCS_DRIVER: gcs

      STORAGE_GCS_KEY_FILENAME: /directus/gcs_key.json
      STORAGE_GCS_BUCKET: bullenetwork-directus-vanil

      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}
    secrets:
      - source: bn_directus_gcs_key
        target: /directus/gcs_key.json

networks:
  public:
    external: true
  internal:


secrets:
  bn_directus_gcs_key:
    external: true

volumes:
  directusDataVol1:
