# stack name: bn_directus

version: "3.9"

services:
  cache:
    # Redis runs on port 6379
    image: redis:7.0.4
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=false

  directus:
    # Directus runs on port 8055
    image: directus/directus:10
    networks:
      - internal
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.http.routers.bn_directus.rule=Host(`vanil.bullenetwork.ch`)
        - traefik.http.routers.bn_directus.entrypoints=websecure
        - traefik.http.routers.bn_directus.tls.certresolver=leresolver
        - traefik.http.services.bn_directus.loadbalancer.server.port=8055
        - traefik.http.routers.bn_directus.middlewares=bn_file_transfer
        - traefik.http.middlewares.bn_file_transfer.buffering.maxRequestBodyBytes=512000000 # 512 MB
    depends_on:
      - cache
    environment:
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      DB_POOL__MIN: 0

      MAX_PAYLOAD_SIZE: '512mb'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS_HOST: 'cache'
      REDIS_PORT: '6379'

      PUBLIC_URL: 'https://vanil.bullenetwork.ch'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      STORAGE_LOCATIONS: gcs

      STORAGE_GCS_PUBLIC_URL: https://console.cloud.google.com/storage/browser/bullenetwork-directus-vanil/
      STORAGE_GCS_DRIVER: gcs

      STORAGE_GCS_KEY_FILENAME: /directus/gcs_key.json
      STORAGE_GCS_BUCKET: bullenetwork-directus-vanil

      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}
    secrets:
      - source: bn_directus_gcs_key
        target: /directus/gcs_key.json

  gcsauth:
    # gcsauth runs on port 3426
    image: ghcr.io/doxa-tech/bullenetwork-constellation-gcsauth:latest
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.http.routers.bn_gcsauth.rule=Host(`gcsauth.bullenetwork.ch`)
        - traefik.http.routers.bn_gcsauth.entrypoints=websecure
        - traefik.http.routers.bn_gcsauth.tls.certresolver=leresolver
        - traefik.http.services.bn_gcsauth.loadbalancer.server.port=3426
    environment:
      GCS_BUCKET_NAME: "bullenetwork-directus-vanil"
      GCS_PRIVATE_PATH: "/config/gcs_key.json"
    secrets:
      - source: bn_directus_gcs_key
        target: /config/gcs_key.json

networks:
  public:
    external: true
  internal:

secrets:
  bn_directus_gcs_key:
    external: true
