version: "3.9"
services:
  osia:
    image: "ghcr.io/nkcr/osia-deploy:latest"
    ports:
      - "3333:3333"
    volumes:
      - "osiaVol2:/data"
    environment:
      INSTAGRAM_TOKEN: ${INSTAGRAM_TOKEN}
volumes:
  osiaVol2:
