# stack name : fs_monitoring
version: "3.9"

services:
  prometheus:
    # Prometheus runs on port 9090
    image: prom/prometheus:latest
    configs:
      - source: fs_prometheus_conf
        target: /etc/prometheus/prometheus.yml
    networks:
      - public
    volumes:
      - promotheusDataVol1:/etc/prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=false

  grafana:
    # Grafana runs on port 3000
    image: grafana/grafana-oss:latest
    networks:
      - public
    volumes:
     - grafanaDataVol1:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.http.routers.fs_monitoring_grafana.rule=Host(`monitoring.doxatech.ch`)
        - traefik.http.routers.fs_monitoring_grafana.entrypoints=websecure
        - traefik.http.routers.fs_monitoring_grafana.tls.certresolver=leresolver
        - traefik.http.services.fs_monitoring_grafana.loadbalancer.server.port=3000

networks:
  public:
    external: true

volumes:
  promotheusDataVol1:
  grafanaDataVol1:

configs:
  fs_prometheus_conf:
    external: true
