# stack name : fs_monitoring
version: "3.9"

services:
  prometheus:
    # Prometheus runs on port 9090
    image: prom/prometheus:latest
    user: root
    configs:
      - source: fs_prometheus_conf
        target: /etc/prometheus/prometheus.yml
    networks:
      - public
      - internal
    volumes:
      - promotheusDataVol1:/etc/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=false

  grafana:
    # Grafana runs on port 3000
    image: grafana/grafana-oss:latest
    networks:
      - public
    volumes:
     - grafanaDataVol1:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.http.routers.fs_monitoring_grafana.rule=Host(`monitoring.doxatech.ch`)
        - traefik.http.routers.fs_monitoring_grafana.entrypoints=websecure
        - traefik.http.routers.fs_monitoring_grafana.tls.certresolver=leresolver
        - traefik.http.services.fs_monitoring_grafana.loadbalancer.server.port=3000

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    networks:
      - internal
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    deploy:
      mode: global
      labels:
        - traefik.enable=false

networks:
  public:
    external: true
  internal:

volumes:
  promotheusDataVol1:
  grafanaDataVol1:

configs:
  fs_prometheus_conf:
    external: true
