# docker build --build-arg DIRECTUS_O2VIE_TOKEN=XXX -t o2vie .
# This container fetches the last o2vie-* tags and downloads the release
# artifact associated to it.
FROM alpine:3.16 AS builder

ARG DIRECTUS_O2VIE_TOKEN

RUN apk update
RUN apk add git
RUN apk add tar

# very ineficient since we only need to fetch the tag
RUN git clone https://github.com/doxa-tech/bullenetwork-constellation.git

WORKDIR /bullenetwork-constellation/
RUN git describe --tags --abbrev=0 --match "o2vie-*" > /tmp/tag

RUN wget "https://github.com/doxa-tech/bullenetwork-constellation/releases/download/$(cat /tmp/tag)/$(cat /tmp/tag).tar.gz"

# we expect the tar.gz to be a extracted as a "public/" folder
RUN tar -zxvf "$(cat /tmp/tag).tar.gz"

FROM nginx:1-alpine

COPY --from=builder /bullenetwork-constellation/public /usr/share/nginx/html