version: "3.9"
services:
  static_websites:
    image: "nginx:1-alpine"
    ports:
      - "4001:80"
    volumes:
      - staticWebsitesVol1:/usr/share/nginx/html:ro
      - nginxConf1:/etc/nginx/conf.d/
  hodor_conf:
    image: "alpine:3.16"
    command: >
      sh -c "
        rm -rf ./hodor-config.json &&
        wget https://raw.githubusercontent.com/doxa-tech/armada/main/static-websites/hodor-config.json &&
        cp -R ./hodor-config.json /tmp/conf/config.json
      "
    volumes:
      - hodor1:/tmp/conf/
  nginx_conf:
    image: "alpine:3.16"
    command: >
      sh -c "
        rm -rf ./nginx.conf &&
        wget https://raw.githubusercontent.com/doxa-tech/armada/main/static-websites/nginx.conf &&
        cp -R ./nginx.conf /tmp/conf/static_websites.conf
      "
    volumes:
      - nginxConf1:/tmp/conf/
  hodor:
    image: "ghcr.io/nkcr/hodor-deploy:latest"
    ports:
      - "3334:3333"
    environment:
      - CONFIG_PATH=/data/config.json
    volumes:
      - "hodor1:/data"
      - "staticWebsitesVol1:/deploy"
    depends_on:
      - hodor_conf
volumes:
  # a shared volume that hodor_conf uses to pass the config to hodor
  hodor1:
  staticWebsitesVol1:
  nginxConf1:
