version: "3.9"
services:
  static_websites:
    image: "nginx:1-alpine"
    ports:
      - "4001:80"
    config:
      - nginx_conf
    volumes:
      - "staticWebsitesVol2:/var/html/:ro"
  hodor:
    image: "ghcr.io/nkcr/hodor-deploy:latest"
    ports:
      - "3334:3333"
    environment:
      - CONFIG_PATH=/data/config.json
      # To avoid cross reference links between volumes, we must downlad the
      # .tar.gz on the same volume as where it will be deployed.
      - TMPDIR=/deploy/
    config:
      - hodor_conf
    volumes:
      - "staticWebsitesVol2:/deploy/"
    networks:
      - public
    deploy:
      mode: replicated
      placement:
        constraints: [ project == bullenetwork ]
      labels:
        - traefik.http.routers.portainer.rule=Host(`dev2.o2vie-chatel.ch`)
        - traefik.http.routers.portainer.rule=Host(`dev2.bullenetwork.ch`)
        - traefik.http.routers.portainer.entrypoints=websecure
        - traefik.http.services.portainer.loadbalancer.server.port=3334
        - traefik.http.routers.portainer.service=portainer
        - traefik.http.routers.portainer.tls.certresolver=leresolver
volumes:
  staticWebsitesVol2:
    external: true
configs:
  hodor_conf:
    file: ./hodor_config.json
  nginx_conf:
    file: ./nginx.conf
