# stack name: bn_static-websites

version: "3.9"

services:
  webserver:
    image: nginx:1-alpine
    configs:
      - source: bn_nginx_conf
        target: /etc/nginx/conf.d/static-websites.conf
    volumes:
      - staticWebsitesVol2:/var/html/:ro
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.project == bullenetwork ]
      labels:
        # webserver
        - traefik.http.routers.bn_static-websites_webserver.rule=Host(`o2vie-chatel.ch`) || Host(`bullenetwork.ch`) || Host(`eebulle.ch`) || Host(`enhaut.eebulle.ch`) || Host(`waykup.ch`)
        - traefik.http.routers.bn_static-websites_webserver.entrypoints=websecure
        - traefik.http.routers.bn_static-websites_webserver.tls.certresolver=leresolver
        - traefik.http.services.bn_static-websites_webserver.loadbalancer.server.port=80
        # redirect
        - traefik.http.routers.bn_quartierlibre.rule=Host(`quartierlibreromont.ch`)
        - traefik.http.routers.bn_quartierlibre.middlewares=quartierlibre-redirect
        - traefik.http.routers.bn_quartierlibre.entrypoints=websecure
        - traefik.http.routers.bn_quartierlibre.tls.certresolver=leresolver
        - traefik.http.middlewares.quartierlibre-redirect.redirectregex.regex=^.*
        - traefik.http.middlewares.quartierlibre-redirect.redirectregex.replacement=https://bullenetwork.ch/quartier-libre
        - traefik.http.middlewares.quartierlibre-redirect.redirectregex.permanent=true

  hodor:
    image: ghcr.io/nkcr/hodor-deploy:latest
    environment:
      - CONFIG_PATH=/data/config.json
      # To avoid cross reference links between volumes, we must downlad the
      # .tar.gz on the same volume as where it will be deployed.
      - TMPDIR=/deploy/
    configs:
      - source: bn_hodor_conf
        target: /data/config.json
    volumes:
      - "staticWebsitesVol2:/deploy/"
      - "hodorVol1:/data/"
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.project == bullenetwork ]
      labels: 
        # hodor
        - traefik.http.routers.bn_static-websites_hodor.rule=Host(`hodor.doxatech.ch`)
        - traefik.http.routers.bn_static-websites_hodor.entrypoints=websecure
        - traefik.http.routers.bn_static-websites_hodor.tls.certresolver=leresolver
        - traefik.http.services.bn_static-websites_hodor.loadbalancer.server.port=3333
        # hodor hooks (authenticated)
        - traefik.http.routers.bn_static-websites_hodor_hook.rule=Host(`hodor.doxatech.ch`) && PathPrefix(`/api/hook/`)
        - traefik.http.routers.bn_static-websites_hodor_hook.entrypoints=websecure
        - traefik.http.routers.bn_static-websites_hodor_hook.tls.certresolver=leresolver
        - traefik.http.routers.bn_static-websites_hodor_hook.service=bn_static-websites_hodor
        # auth
        - traefik.http.middlewares.bn_hodor-auth.basicauth.users=hodor:${HODOR_PWD}
        # middlewares
        - traefik.http.routers.bn_static-websites_hodor_hook.middlewares=bn_hodor-auth

networks:   
  public:
    external: true

configs:
  bn_hodor_conf:
    external: true
  bn_nginx_conf:
    external: true

volumes:
  staticWebsitesVol2:
  hodorVol1:
