# stack name: bn_static-websites

version: "3.9"

services:
  webserver:
    image: "nginx:1-alpine"
    ports:
      - "4001:80"
    config:
      - nginx_conf
    volumes:
      - "staticWebsitesVol2:/var/html/:ro"
  hodor:
    image: "ghcr.io/nkcr/hodor-deploy:latest"
    ports:
      - "3334:3333"
    environment:
      - CONFIG_PATH=/data/config.json
      # To avoid cross reference links between volumes, we must downlad the
      # .tar.gz on the same volume as where it will be deployed.
      - TMPDIR=/deploy/
    config:
      - hodor_conf
    volumes:
      - "staticWebsitesVol2:/deploy/"
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.project == bullenetwork ]
      labels:
        # webserver
        - traefik.http.routers.bn_static-websites_webserver.rule="Host(`dev2.o2vie-chatel.ch`) || Host(`dev2.bullenetwork.ch`)"
        - traefik.http.routers.bn_static-websites_webserver.entrypoints=websecure
        - traefik.http.routers.bn_static-websites.tls.certresolver=leresolver
        - traefik.http.routers.bn_static-websites_webserver.service=bn_static-websites_webserver
        - traefik.http.services.bn_static-websites_webserver.loadbalancer.server.port=4001
        # hodor
        - traefik.http.routers.bn_static-websites_hodor.rule=Host(`hodor.doxatech.ch`)
        - traefik.http.routers.bn_static-websites_hodor.entrypoints=websecure
        - traefik.http.routers.bn_static-websites_hodor.tls.certresolver=leresolver
        - traefik.http.routers.bn_static-websites_hodor.service=bn_static-websites_hodor
        - traefik.http.services.bn_static-websites_hodor.loadbalancer.server.port=3334

networks:
  public:
    external: true

configs:
  hodor_conf:
    file: ./hodor_config.json
  nginx_conf:
    file: ./nginx.conf

volumes:
  staticWebsitesVol2:
