# stack name : fs_wiki
version: '3'

services:
  docmost:
    # docmost runs on port 3000
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'https://wiki.doxatech.ch'
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: 'postgresql://docmost:${DB_PASSWORD}@${DB_HOST}:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
      MAIL_DRIVER: smtp
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: "true"
      MAIL_FROM_ADDRESS: noreply@doxatech.ch
      MAIL_FROM_NAME: Docmost
    networks:
      - public
      - internal
    restart: unless-stopped
    volumes:
      - docmostDataVol1:/app/data/storage
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.http.routers.fs_wiki_docmost.rule=Host(`wiki.doxatech.ch`)
        - traefik.http.routers.fs_wiki_docmost.entrypoints=websecure
        - traefik.http.routers.fs_wiki_docmost.tls.certresolver=leresolver
        - traefik.http.services.fs_wiki_docmost.loadbalancer.server.port=3000

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - docmostRedisDataVol1:/data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=false

volumes:
  docmostDataVol1:
  docmostRedisDataVol1:

networks:
  public:
    external: true
  internal:
