version: "3.2"

services:
  traefik:
    image: traefik:latest
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.network=public
      - --api.dashboard=true
      - --log.level=ERROR
      - --certificatesresolvers.leresolver.acme.dnschallenge=true
      - --certificatesresolvers.leresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.leresolver.acme.email=kocher.ke@gmail.com
      - --certificatesresolvers.leresolver.acme.storage=acme.json
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=<TOKEN>
    ports:
      - 80:80
      - 443:443
    networks:
      - public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.http.routers.dashboard.rule=Host(`compass.doxatech.ch`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        - traefik.http.routers.dashboard.service=api@internal
        - traefik.http.routers.dashboard.entrypoints=websecure
        - traefik.http.routers.dashboard.tls.certresolver=leresolver
        # Dummy service for Swarm port detection. The port can be any valid integer value.
        - traefik.http.services.dummy-svc.loadbalancer.server.port=9999
        # auth
        - traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$rfP66Nwp$$JWxEZZKay.jqQcKUxGk7n1
        # middlewares
        - traefik.http.routers.dashboard.middlewares=dashboard-auth
        # redirect www to non-www
        - traefik.http.middlewares.redirect-www.redirectregex.regex=^https://www\.(.+)
        - traefik.http.middlewares.redirect-www.redirectregex.replacement=https://$${1}
        - traefik.http.middlewares.redirect-www.redirectregex.permanent=true

  agent:
    image: portainer/agent:latest
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      labels:
        - traefik.enable=false

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - public
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.http.routers.portainer.rule=Host(`flagship.doxatech.ch`)
        - traefik.http.routers.portainer.entrypoints=websecure
        - traefik.http.routers.portainer.tls.certresolver=leresolver
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        
networks:
  public:
    external: true
  agent_network:
    external: true

volumes:
  portainer_data: