# stack name: bn_o2vie

version: "3.9"
services:
  osia:
    image: "ghcr.io/nkcr/osia-deploy:latest"
    ports:
      - "3333:3333"
    volumes:
      - "osiaVol2:/data"
    environment:
      INSTAGRAM_TOKEN: ${INSTAGRAM_TOKEN}
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.project == bullenetwork]
      labels:
        - traefik.http.routers.bn_o2vie_osia.rule=Host(`osia.o2vie-chatel.ch`)
        - traefik.http.routers.bn_o2vie_osia.entrypoints=websecure
        - traefik.http.routers.bn_o2vie_osia.tls.certresolver=leresolver
        - traefik.http.routers.bn_o2vie_osia.service=bn_o2vie_osia
        - traefik.http.services.bn_o2vie_osia.loadbalancer.server.port=3333

networks:
  public:
    external: true

volumes:
  osiaVol2:
